### ISSUE TITLE
Trouble submitting molecules in NaPLeS website

### ISSUE THREAD

**Issue by angel362** [mSorok/NPlsWeb#5]
Hi,

I am having trouble submitting molecules directly to the NaPLeS website. Every time I upload or draw a molecule the platform displays "Warning! contains unknown fragments:". I already tried every available uploading option.
![Screen Shot 2020-10-20 at 5 13 32 PM](https://user-images.githubusercontent.com/73199809/96645155-2c56af80-12f8-11eb-903d-fa08961b0bfb.png)

**Comment by mSorok** [comment]
Thank you for notifying me about this! The service is now back to the normal.

**Comment by angel362** [comment]
Hi,
Thanks for your quick response! It worked with the first molecule I uploaded, but now the issue came back.
![Screen Shot 2020-10-20 at 7 45 46 PM](https://user-images.githubusercontent.com/73199809/96655992-e6f0ad00-130c-11eb-9120-c209c5f71b57.png)

**Comment by mSorok** [comment]
Weird, works well for me. 
I restarted everything and cleared the logs, can you please try now and confirm that the service is back?

**Comment by angel362** [comment]
Yes, it is back. Thanks!
