### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by aclcoelho** [mSorok/NPlsWeb#7]
Hi! 

When trying to use the online tool, it just loads for a long time and then opens an Whitelabel Error Page.
This is what it says:

"""
_Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Apr 16 18:26:04 UTC 2021
There was an unexpected error (type=Internal Server Error, status=500).
Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection_
"""
I would really like to use the tool for some quick checking, would it be possible to be fixed?

Thank you!

**Comment by mSorok** [comment]
Hi, 

sorry about the interruption of service, I don't know why it went down, but I restored it.

Thank you for reporting!
